theme: jekyll-theme-minimal
title: Hamel Husain
description: A collection of technical blogs and talks on machine learning.
show_downloads: false
google_analytics: UA-57531313-2
logo: ./hamel.jpg
social-network-links:
  linkedin: hamelhusain
  twitter: HamelHusain
  github: hamelsmu
  
