project:
  type: website

website:
  title: "Hamel Husain"
  navbar:
    background: dark
    pinned: true
    collapse: false
    left:
    - text: 📮 Blog
      file: index.qmd
    - text: 👨🏽‍💻 About
      file: about.qmd
    - text: Open Source
      icon: github
      file: opensource.qmd
    - text: 🎤 Talks 
      file: talks.qmd
    - text: 📚 Notes
      file: notes/index.qmd
  sidebar:
    - title: Notes
      collapse-level: 1
      style: docked
      contents: notes/**

format:
  html:
    theme: [solar, custom.scss]
    css:
      - styles.css
    toc: true



