project:
  type: website

website:
  title: "Hamel Husain"
  navbar:
    background: dark
    collapse: false
    left:
    - text: Home
      href: index.qmd
    - text: Blogs
      href: blog_listings/index.qmd
    - text: Open Source
      href: opensource.qmd
    - text: Talks
      href: talks.qmd
    - text: test
      href: hidden_blog/index.qmd
  # sidebar:
  #   - id: open-source
  #     text: Open Source
  #     collapse-level: 1
  #     style: docked
  #     search: true
  #     contents: [opensource.qmd]
    # contents:
    # - opensource.qmd
    # - section: Blogs
    #   contents:
    #     - guest-blog.qmd
    #     - c

format:
  html:
    theme: [solar, custom.scss]
    css:
      - styles.css
    toc: true



