on: issue_comment 
name: Preview on Netlify

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  preview:
    if: (github.event.issue.pull_request != null) && contains(github.event.comment.body, '/preview')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Setup Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: 'pre-release'
        
    - name: install other dependencies
      run: pip install nbformat # you don't need this line, this is unique to hamel
    
    - run: quarto render
    
    # See https://github.com/netlify/actions/tree/master/cli
    - name: Publish preview with Netlify
      id: publish
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=_site # Quarto renders everything to a _site/ folder
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        
    - name: Make a comment with the GitHub API
      uses: actions/github-script@v6
      if: steps.publish.outcome == 'success' 
      with:
        script: |
           var msg = `You can preview your site here: ${process.env.URL}`
           github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            })
      env:
        URL: "${{ steps.publish.outputs.NETLIFY_URL }}"
